[package]
name = "polyprops"
version = "1.0.2"
authors = ["Kyle Lessa"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
name = "polyprops"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
